### ISSUE TITLE
beginnings and endings

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-people-use-web-videos#286]
Background: lots of discussion in [Sign-off needs adjusting #55](https://github.com/w3c/wai-people-use-web-videos/issues/55)

## ending
* [ ] actor quote(s) **_<- must be finalized before filming_**
* [ ] narrator catchphrase (e.g., "Accessibility: It's about people.")
* [ ] catchphrase longer version for pages? (https://github.com/w3c/wai-people-use-web-videos/issues/55#issuecomment-1272207990)
* [ ] end plate text

## landing page https://github.com/w3c/wai-people-use-web-videos/issues/55#issuecomment-1287970596
* [ ] confirm new landing page: w3.org/WAI/people 
* [ ] SLH draft it

## front plate
* [ ] front plate text, see [SAZ comment](https://github.com/w3c/wai-people-use-web-videos/issues/55#issuecomment-1288129398)
* [ ] front plate visual design, see [SAZ comment](https://github.com/w3c/wai-people-use-web-videos/issues/55#issuecomment-1288129398)
